Iot 774 update http example
ClearBlade/nodejs-iot pull request #29
Opened 2022-11-24 13:11 UTC by sky-sharma

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/nodejs-iot/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

2022-11-28 18:05 UTC, clarkbynum requested changes

2022-11-28 18:05 UTC, clarkbynum commented on samples/http_example/cloudiot_http_example.js
> +  console.log(`registryCreds: ${JSON.stringify(registryCredsObj)}`);
Can this console log be removed? Might be noisy

2022-11-28 18:15 UTC, sky-sharma commented on samples/http_example/cloudiot_http_example.js
> +  } catch (err) {
Do you mean a throw new error inside the catch (err) {...} ?

2022-11-28 18:22 UTC, clarkbynum commented on samples/http_example/cloudiot_http_example.js
> +  } catch (err) {
Yes, you can re-throw the error with `throw err`

2022-11-29 15:47 UTC, clarkbynum approved these changes

2022-11-29 16:13 UTC, merged